# For more information about the configurations used
# in this file, please see the Travis CI documentation.
#
# https://docs.travis-ci.com

language: node_js

matrix:
  include:

    - os: linux
      dist: trusty
      before_script:
        - gem install awesome_bot
      node_js:
        - node
      script:
        - ./.travis/check-links.sh

    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - google-chrome
          packages:
            - google-chrome-stable
      before_script:
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
        - sleep 3
      node_js:
        - node
      script:
        - npm run test-on-travis

    - os: osx
      osx_image: xcode8.3
      before_install:
        - brew cask install google-chrome
      node_js:
        - node
      script:
        - npm run test-on-travis

notifications:
  email:
    on_failure: always
    on_success: never
