# For more information about the configurations used
# in this file, please see the Travis CI documentation.
#
# https://docs.travis-ci.com

env:
  global:
    # TRAVIS_API_TOKEN
    - secure: "onk4EVKZzabHQB+P1RrzSsnZDm9KGqvZrSHCqkPV/3FYz7FDYGfsXtDvY64Zdjyb3EMfZL4A+DV+O5nCIzD/P0fIPDXZMH6pDy77Mnxg93+jwyCwuA40erLG8SQ5jMF8RK/UPun4yA1p3f0mns3pozYf5F4Ron/CiSsfsMnAYbm9kw5wPPQGVHae+vDOJ82fFgxwYuXpQ6lFIdBUtEg2wiIH0xs/YLr8w07a2NDXBOli/9xTqFFzUV9cjcIx1+/QIBVMY1lVRsY4kLj17orD8dMejMFnprroJrUGG66CgBMq5ZPQNGahI+aZ9cLippbbSFu1eZgB5E1tQjptrMIP5jpNGcD7KHZLG8KdzBr+3UuNul4fZpl+UHmnX4C1itFkr18HRd2pJJynLio2O2hMjHz6o7YfV5Bsj4qF+tbemx3491K3vwNH5HU+4//DN1Rvj+7CK25Lsm8R/TDJbMwuHVZoXjaGYrot5S4cLvNj82gEXuzkNlyWCKKuFfrie206rAnAgJ1TNq0Q8BUpgFETv/P/F5z40Efi2V9dsXy0QpaAFAZOxKF3wB337u6nZT6oM6GjVL446XVRqENtRGUdXreccBzmBZTa81nz8XHg6C0vtdNP8/GG4pRnCoxMYKHmoQtvYuKhly3vjgoc3Yt+ZyCuDQs066r9s76noXhBFYY="

language: node_js

matrix:
  include:

    # 1. Build used for checking links and, if needed,
    #    to trigger a rebuild of the site.

    - os: linux
      dist: trusty
      install:
        - gem install awesome_bot
      node_js:
        - node
      script:
        - ./.travis/check-links.sh && ./.travis/trigger-site-update.sh

    # 2. Build used for running the tests for sonar on Ubuntu.

    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - google-chrome
          packages:
            - google-chrome-stable
      node_js:
        - node
      script:
        - npm run test-on-travis

    # 3. Build used for running the tests for sonar on macOS.

    - os: osx
      osx_image: xcode8.3
      before_install:
        - brew cask install google-chrome
      node_js:
        - node
      script:
        - npm run test-on-travis

notifications:
  email:
    on_failure: always
    on_success: never
