# For more information about the configurations used
# in this file, please see the Travis CI documentation.
#
# https://docs.travis-ci.com

language: node_js

matrix:
  include:

    - os: linux
      dist: trusty

      addons:
        apt:
          sources:
            - google-chrome
          packages:
            - google-chrome-stable
      before_script:
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
        - sleep 3
      node_js:
        - node

    - os: osx

      before_install:
        - brew cask install google-chrome
      node_js:
        - node
