parameters:
  name: ''
  vmImage: ''

jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    matrix:
      node_8_x:
        node_version: 8.x
      node_10_x:
        node_version: 10.x
      node_11_x:
        node_version: 11.x
  steps:
  - script: brew update && brew cask install google-chrome
    condition: eq(variables['Agent.OS'], 'Darwin')
    displayName: 'Install Chrome'
  - task: NodeTool@0
    inputs:
      versionSpec: $(node_version)
  - task: geeklearningio.gl-vsts-tasks-yarn.yarn-installer-task.YarnInstaller@2
    displayName: 'Use Yarn 1.x'
    inputs:
      checkLatest: true
  - script: yarn
    displayName: 'Install dependencies'
  - script: yarn test
    displayName: 'Test'
